import Link from "next/link";
import { LegalPage } from "@/components/LegalPage";
export const metadata = {title: "Política de cookies | Lidia Villanueva Bolívar"};
export default function Page() { return <LegalPage title="Política de cookies">
<h2>1. Qué son las cookies</h2><p>Son pequeños archivos que una web almacena en el navegador. Otras tecnologías, como el almacenamiento local y las cachés, también pueden guardar información en tu dispositivo. Su tratamiento depende de su finalidad, no únicamente de su nombre.</p>
<h2>2. Qué utiliza esta web</h2><p>El código de esta versión no instala cookies propias ni de terceros, no guarda preferencias en localStorage o sessionStorage y no incorpora analítica, píxeles publicitarios, vídeos o mapas de terceros. Las tipografías son del sistema y la ilustración se sirve desde la propia web.</p><p>En producción, la aplicación utiliza un service worker y Cache Storage para conservar recursos de la web y facilitar su carga. Es una caché técnica del mismo origen; no contiene identificadores publicitarios ni se utiliza para seguir tu navegación. Los recursos se renuevan con las versiones de la web y pueden permanecer hasta su actualización, eliminación por el navegador o borrado manual. El navegador también puede mantener su caché HTTP habitual.</p>
<h2>3. Consentimiento</h2><p>Esta configuración no incorpora tecnologías opcionales de seguimiento para las que solicitar consentimiento. Por eso no se muestra un banner de aceptar o rechazar. Antes de incorporar analítica, publicidad u otras tecnologías no exentas, será necesario informar y permitir aceptar, rechazar y modificar la elección, bloqueándolas hasta obtener el consentimiento correspondiente.</p><p>La configuración del alojamiento definitivo deberá verificarse antes de publicar, pues podría añadir cookies no presentes en el código de la aplicación.</p>
<h2>4. Cómo borrar el almacenamiento</h2><p>Puedes eliminar los datos del sitio desde los ajustes de privacidad de tu navegador, buscando el dominio en la sección de cookies y datos de sitios. Esto permite borrar la caché y, según el navegador, el registro de la aplicación sin conexión. Al volver a visitar la web pueden generarse de nuevo los recursos técnicos. El bloqueo de almacenamiento puede afectar a la carga o disponibilidad sin conexión.</p>
<h2>5. Más información</h2><p>Consulta la <Link href="/es/privacy-policy">política de privacidad</Link> para conocer al responsable y tus derechos. Referencia: <a href="https://www.aepd.es/guias/guia-cookies.pdf">Guía sobre el uso de cookies de la AEPD</a>.</p>
</LegalPage>; }
