import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
const classes = [
 {n:"01",title:"Un espacio para ti",tag:"PILATES INDIVIDUAL",body:"Atención personalizada para conocer tu punto de partida y explorar el movimiento a tu ritmo. Cada sesión se adapta a ti.",icon:"◌"},
 {n:"02",title:"Moverse en compañía",tag:"GRUPOS REDUCIDOS",body:"La energía de compartir, con el cuidado de sentirte acompañada. Una práctica cercana en la que cada persona tiene su espacio.",icon:"❋"},
 {n:"03",title:"Nunca es tarde",tag:"PILATES SUAVE",body:"Una invitación a empezar, retomar o bajar el ritmo. Movimientos progresivos y conscientes para descubrir nuevas posibilidades.",icon:"〰"},
];
export default function HomePage() {
 const email=process.env.NEXT_PUBLIC_CONTACT_EMAIL;
 return <><a className="skip" href="#contenido">Saltar al contenido</a><Header/><main id="contenido">
 <section className="hero wrap" id="inicio"><div className="hero-copy"><p className="eyebrow"><span/> UN MOMENTO PARA VOLVER A TI</p><h1>Muévete con calma.<br/>Vive con <em>plenitud.</em></h1><p className="intro">Pilates para escuchar tu cuerpo, encontrar tu equilibrio y disfrutar del movimiento. A cualquier edad. A tu manera.</p><a className="button" href="#clases">Encuentra tu práctica <span>↗</span></a><div className="hero-note"><span className="tiny-flower">✳</span><p>Más de 15 años acompañando<br/><strong>cada pequeño gran avance.</strong></p></div></div><div className="hero-art"><div className="art-image" role="img" aria-label="Ilustración de una mujer practicando Pilates en un espacio sereno"/><span className="art-label">RESPIRA. CONECTA. FLUYE.</span><div className="floating-note"><span>Un cuerpo, mil posibilidades.</span><small>Tu bienestar empieza contigo</small></div></div><a href="#sobre-mi" className="scroll-note">DESCUBRE MI HISTORIA <span>↓</span></a></section>
 <div className="ribbon"><span>Movimiento consciente</span><i>✳</i><span>Atención cercana</span><i>✳</i><span>Respeto por tu ritmo</span><i>✳</i><span>Bienestar a cualquier edad</span></div>
 <section className="about wrap section" id="sobre-mi"><div className="about-art"><div className="line-art">lv.</div><p>La experiencia me ha enseñado<br/>a escuchar. El Pilates,<br/><em>a seguir descubriendo.</em></p><span>LIDIA VILLANUEVA BOLÍVAR</span></div><div className="about-copy"><p className="eyebrow">ENCANTADA, SOY LIDIA</p><h2>59 años de vida.<br/>Una forma de <em>sentirla.</em></h2><p>Creo en un movimiento que acompaña, que se adapta y que nos ayuda a estar más presentes. A mis 59 años, sigo encontrando en el Pilates una manera de conectar conmigo y disfrutar de lo cotidiano.</p><p>Llevo más de 15 años vinculada al Pilates. Mi manera de enseñar nace de esa experiencia: escuchar primero, cuidar los detalles y respetar el momento de cada persona.</p><div className="stats"><div><strong>15+</strong><span>años de experiencia</span></div><div><strong>59</strong><span>años, en movimiento</span></div><div><strong>Tu ritmo</strong><span>siempre es el punto de partida</span></div></div></div></section>
 <section className="classes section" id="clases"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">TU PRÁCTICA, TU ESPACIO</p><h2>Hay una forma de Pilates<br/><em>para ti.</em></h2></div><p>No necesitas experiencia previa.<br/>Solo ganas de dedicarte un momento.</p></div><div className="cards">{classes.map(c=><article className="class-card" key={c.n}><div className="card-top"><span>{c.n}</span><span className="class-icon" aria-hidden="true">{c.icon}</span></div><p className="eyebrow">{c.tag}</p><h3>{c.title}</h3><p>{c.body}</p><a href="#contacto">Hablemos de esta práctica <span>↗</span></a></article>)}</div></div></section>
 <section className="philosophy wrap section" id="filosofia"><span className="flower" aria-hidden="true">✳</span><p className="eyebrow">MI FORMA DE ENTENDER EL PILATES</p><h2>No se trata de hacerlo perfecto.<br/>Se trata de hacerlo <em>tuyo.</em></h2><p>Respirar antes de empezar. Prestar atención a lo pequeño. Celebrar el proceso.<br/>Porque cuidarse también puede ser un momento amable, sencillo y lleno de calma.</p><div className="values"><span>01 / Escuchar</span><span>02 / Acompañar</span><span>03 / Disfrutar</span></div></section>
 <section className="contact wrap" id="contacto"><div><p className="eyebrow">EL PRIMER PASO, SIN PRISA</p><h2>Hagamos espacio<br/>para <em>tu bienestar.</em></h2><p>Cuéntame qué tipo de clases buscas y tu disponibilidad.<br/>Encontraremos juntas una manera de empezar.</p></div><div className="contact-action">{email ? <><a className="button" href={`mailto:${email}?subject=Me%20gustaría%20conocer%20tus%20clases`}>Hablemos de Pilates <span>↗</span></a><p>Una conversación, sin compromiso.</p></> : <><span className="contact-status">Información de contacto próximamente</span><p>Este espacio se está preparando.<br/>Pronto podrás consultar horarios y disponibilidad.</p></>}</div></section>
 </main><Footer/></>;
}
